language: dart
sudo: false
dart:
  - stable
  - dev
## The dev channel is stable enough, report failures now.
# env: # important: w/o this top-level env, no job will be allowed to fail.
# matrix:
#   allow_failures:
#   - dart: dev
with_content_shell: true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: ./tool/travis.sh

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
