name: stagehand
version: 0.0.2
description: A scaffolding generator for your Dart projects. Stagehand helps you get set up!
homepage: https://github.com/sethladd/stagehand
authors:
- Seth Ladd <sethladd@gmail.com>
- Devon Carew <devoncarew@google.com>
dev_dependencies:
  args: any
  path: any
  unittest: any
