name: stagehand
version: 0.0.3
description: A scaffolding generator for your Dart projects. Stagehand helps you get set up!
homepage: https://github.com/sethladd/stagehand
authors:
- Seth Ladd <sethladd@gmail.com>
- Devon Carew <devoncarew@google.com>
dependencies:
  args: ">=0.12.0+1 <0.13.0"
  path: ">=1.3.0 <2.0.0"
dev_dependencies:
  unittest: any
