name: {{projectName}}
version: 0.0.1
description: A simple console application.
#author: {{author}} <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'
